services:
    regiones_ciudad_type:
        class: SfVen\Bundle\RegionesBundle\Form\Type\CiudadType
        tags:
            - { name: form.type, alias: ciudad }
            
    regiones_estado_type:
        class: SfVen\Bundle\RegionesBundle\Form\Type\EstadoType
        tags:
            - { name: form.type, alias: estado }
